New Branch, tasks completed
Andrejs24/CodelexHomework pull request #3
Opened 2023-05-10 13:14 UTC by Andrejs24

Nedaudz pacakarejos, bet ceru ka tagad ir labi soreiz rada 15 failus (changed)

2023-05-12 10:48 UTC, janistumpelis requested changes
Pāris sīkumi jāpielabo un būs ok, galvenais faktiski formatting.

2023-05-12 10:48 UTC, janistumpelis commented on src/main/java/io/codelex/arithmetic/HomeworkTasks/Exercise4.java
> +int n = 10;
Formatting - pamanīju, ka arī citās vietās trūkst. Pārformatē visus failus pie reizes un droši vien slēdz iekšā, lai automātiski noformatē failus.

2023-05-12 10:48 UTC, janistumpelis commented on src/main/java/io/codelex/arithmetic/HomeworkTasks/Exercise6.java
> +            if (divideBy3 && divideBy5 && divideBy7) {
Šito varēja nedaudz īsāk uzrakstīt (šis ir pseidokods, jebšu tīri lai ideju saprastu):
if (divideBy3) print Coza
if (divideBy5) print Loza
if (divideBy7) print Woza
if (!divideBy3 && !divideBy5 && !divideBy7) print i + " "

2023-05-13 06:59 UTC, Andrejs24 commented
Jāni ar to visu, izlabot un jauno pull request taisīt un mergot main branchā? vai atkal tev linku atsūtīt?


> On 12 May 2023, at 13:48, janistumpelis ***@***.***> wrote:
> 
> 
> @janistumpelis requested changes on this pull request.
> 
> Pāris sīkumi jāpielabo un būs ok, galvenais faktiski formatting.
> 
> In src/main/java/io/codelex/arithmetic/HomeworkTasks/Exercise4.java <https://github.com/Andrejs24/CodelexHomework/pull/3#discussion_r1192210688>:
> 
> > @@ -0,0 +1,13 @@
> +package io.codelex.arithmetic.HomeworkTasks;
> +
> +public class Exercise4 {
> +    public static void main(String[] args) {
> +int n = 10;
> Formatting - pamanīju, ka arī citās vietās trūkst. Pārformatē visus failus pie reizes un droši vien slēdz iekšā, lai automātiski noformatē failus.
> 
> In src/main/java/io/codelex/arithmetic/HomeworkTasks/Exercise6.java <https://github.com/Andrejs24/CodelexHomework/pull/3#discussion_r1192212979>:
> 
> > +package io.codelex.arithmetic.HomeworkTasks;
> +
> +//Write a program called CozaLozaWoza which prints the numbers 1 to 110,
> +// 11 numbers per line. The program shall print "Coza" in place of the numbers which are multiples of 3,
> +// "Loza" for multiples of 5, "Woza" for multiples of 7,
> +// "CozaLoza" for multiples of 3 and 5, and so on.
> +
> +public class Exercise6 {
> +    public static void main(String[] args) {
> +        for (int i = 1; i <= 110; i++) {
> +            boolean divideBy3 = (i % 3 == 0);
> +            boolean divideBy5 = (i % 5 == 0);
> +            boolean divideBy7 = (i % 7 == 0);
> +
> +
> +            if (divideBy3 && divideBy5 && divideBy7) {
> Šito varēja nedaudz īsāk uzrakstīt (šis ir pseidokods, jebšu tīri lai ideju saprastu):
> if (divideBy3) print Coza
> if (divideBy5) print Loza
> if (divideBy7) print Woza
> if (!divideBy3 && !divideBy5 && !divideBy7) print i + " "
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Andrejs24/CodelexHomework/pull/3#pullrequestreview-1424242198>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQGSN7L25JTVFLBFAQYWRJTXFYIOZANCNFSM6AAAAAAX4XJCUU>.
> You are receiving this because you authored the thread.
>

2023-05-18 19:16 UTC, merged